
samples: 'samples.tsv'
tmpdir: '/tmp/viral-ampliseq-assembly'

# fmd, csf, ebola, zika
organism: 'csf'

samtools:
  threads: 56

mash:
  threads: 8
  kmer_size: 16
  n_sketches: 10000

bwa:
  threads: 56

spades:
  threads: 56
  tmp: '/tmp/viral-ampliseq-assembly/spades'
  careful: true
  meta: false
  args: ''
