name: viral-ampliseq-assembly-1.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.9
  - bwa=0.7.17
  - clearcut=1.0.9
  - fastqc=0.11.8
  - freebayes=1.3.1
  - iqtree=1.6.8
  - mafft=7.407
  - mash=2.1
  - multiqc=1.7
  - openssl=1.1
  - picard=2.20.5
  - samclip=0.2
  - samtools=1.9
  - snippy=4.4.1
  - snpeff=4.3.1t
  - spades=3.13.1
  - trimmomatic=0.39
  - python=3.6.6
  - pip=19.2.1
  - pip:
    - biopython==1.74
    - bcbio-gff==0.6.6
    - click==7.0
    - pandas==0.25.0
    - ete3==3.1.1
    - quast==5.0.2
    - jupyter==1.0.0
    - nbformat==4.4.0
    - nbconvert==5.5.0
    - bokeh==1.3.2
    - shiptv==0.2.0
